# converts a string to html
proc htmlentities {sStr} {
  regsub -all "&"      ${sStr}  {\&amp;}    sStr1
  regsub -all "<"      ${sStr1} {\&lt;}     sStr2
  regsub -all ">"      ${sStr2} {\&gt;}     sStr1
  regsub -all "\u00c0" ${sStr1} {\&Agrave;} sStr2
  regsub -all "\u00c1" ${sStr2} {\&Aacute;} sStr1
  regsub -all "\u00c5" ${sStr1} {\&Acirc;}  sStr2
  regsub -all "\u00c3" ${sStr2} {\&Atilde;} sStr1
  regsub -all "\u00c4" ${sStr1} {\&Auml;}   sStr2
  regsub -all "\u00c2" ${sStr2} {\&Aring;}  sStr1
  regsub -all "\u00c6" ${sStr1} {\&AElig;}  sStr2
  regsub -all "\u00c7" ${sStr2} {\&Ccedil;} sStr1
  regsub -all "\u00c8" ${sStr1} {\&Egrave;} sStr2
  regsub -all "\u00c9" ${sStr2} {\&Eacute;} sStr1
  regsub -all "\u00ca" ${sStr1} {\&Ecirc;}  sStr2
  regsub -all "\u00cb" ${sStr2} {\&Euml;}   sStr1
  regsub -all "\u00cc" ${sStr1} {\&Igrave;} sStr2
  regsub -all "\u00cd" ${sStr2} {\&Iacute;} sStr1
  regsub -all "\u00ce" ${sStr1} {\&Icirc;}  sStr2
  regsub -all "\u00cf" ${sStr2} {\&Iuml;}   sStr1
  regsub -all "\u00d0" ${sStr1} {\&ETH;}    sStr2
  regsub -all "\u00d1" ${sStr2} {\&Ntilde;} sStr1
  regsub -all "\u00d2" ${sStr1} {\&Ograve;} sStr2
  regsub -all "\u00d3" ${sStr2} {\&Oacute;} sStr1
  regsub -all "\u00d4" ${sStr1} {\&Ocirc;}  sStr2
  regsub -all "\u00d5" ${sStr2} {\&Otilde;} sStr1
  regsub -all "\u00d6" ${sStr1} {\&Ouml;}   sStr2
  regsub -all "\u00d7" ${sStr2} {\&times;}  sStr1
  regsub -all "\u00d8" ${sStr1} {\&Oslash;} sStr2
  regsub -all "\u00d9" ${sStr2} {\&Ugrave;} sStr1
  regsub -all "\u00da" ${sStr1} {\&Uacute;} sStr2
  regsub -all "\u00db" ${sStr2} {\&Ucirc;}  sStr1
  regsub -all "\u00dc" ${sStr1} {\&Uuml;}   sStr2
  regsub -all "\u00dd" ${sStr2} {\&Yacute;} sStr1
  regsub -all "\u00de" ${sStr1} {\&THORN;}  sStr2
  regsub -all "\u00df" ${sStr2} {\&szlig;}  sStr1
  regsub -all "\u00e0" ${sStr1} {\&agrave;} sStr2
  regsub -all "\u00e1" ${sStr2} {\&aacute;} sStr1
  regsub -all "\u00e2" ${sStr1} {\&acirc;}  sStr2
  regsub -all "\u00e3" ${sStr2} {\&atilde;} sStr1
  regsub -all "\u00e4" ${sStr1} {\&auml;}   sStr2
  regsub -all "\u00e5" ${sStr2} {\&aring;}  sStr1
  regsub -all "\u00e6" ${sStr1} {\&aelig;}  sStr2
  regsub -all "\u00e7" ${sStr2} {\&ccedil;} sStr1
  regsub -all "\u00e8" ${sStr1} {\&egrave;} sStr2
  regsub -all "\u00e9" ${sStr2} {\&eacute;} sStr1
  regsub -all "\u00ea" ${sStr1} {\&ecirc;}  sStr2
  regsub -all "\u00eb" ${sStr2} {\&euml;}   sStr1
  regsub -all "\u00ec" ${sStr1} {\&igrave;} sStr2
  regsub -all "\u00ed" ${sStr2} {\&iacute;} sStr1
  regsub -all "\u00ee" ${sStr1} {\&icirc;}  sStr2
  regsub -all "\u00ef" ${sStr2} {\&iuml;}   sStr1
  regsub -all "\u00f0" ${sStr1} {\&eth;}    sStr2
  regsub -all "\u00f1" ${sStr2} {\&ntilde;} sStr1
  regsub -all "\u00f2" ${sStr1} {\&ograve;} sStr2
  regsub -all "\u00f3" ${sStr2} {\&oacute;} sStr1
  regsub -all "\u00f4" ${sStr1} {\&ocirc;}  sStr2
  regsub -all "\u00f5" ${sStr2} {\&otilde;} sStr1
  regsub -all "\u00f6" ${sStr1} {\&ouml;}   sStr2
  regsub -all "\u00f7" ${sStr2} {\&divide;} sStr1
  regsub -all "\u00f8" ${sStr1} {\&oslash;} sStr2
  regsub -all "\u00f9" ${sStr2} {\&ugrave;} sStr1
  regsub -all "\u00fa" ${sStr1} {\&uacute;} sStr2
  regsub -all "\u00fb" ${sStr2} {\&ucirc;}  sStr1
  regsub -all "\u00fc" ${sStr1} {\&uuml;}   sStr2
  regsub -all "\u00fd" ${sStr2} {\&yacute;} sStr1
  regsub -all "\u00fe" ${sStr1} {\&thorn;}  sStr2
  regsub -all "\u00ff" ${sStr2} {\&yuml;}   sStr1
  regsub -all "\u00a2" ${sStr1} {\&cent;}   sStr2
  regsub -all "\u00a3" ${sStr2} {\&pound;}  sStr1
  regsub -all "\u00a4" ${sStr1} {\&curren;} sStr2
  regsub -all "\u00a5" ${sStr2} {\&yen;}    sStr1
  regsub -all "\u00a7" ${sStr1} {\&sect;}   sStr2
  regsub -all "\u00aa" ${sStr2} {\&ordf;}   sStr1
  regsub -all "\u00AB" ${sStr1} {\&laquo;}  sStr2
  regsub -all "\u00BB" ${sStr2} {\&raquo;}  sStr1
  regsub -all "\u00ae" ${sStr1} {\&reg;}    sStr2
  regsub -all "\u00b0" ${sStr2} {\&deg;}    sStr1
  regsub -all "\u00b1" ${sStr1} {\&plusmn;} sStr2
  regsub -all "\u00b2" ${sStr2} {\&sup2;}   sStr1
  regsub -all "\u00b3" ${sStr1} {\&sup3;}   sStr2
  regsub -all "\u00b4" ${sStr2} {\&acute;}  sStr1
  regsub -all "\u00b5" ${sStr1} {\&micro;}  sStr2
  regsub -all "\u00b7" ${sStr2} {\&middot;} sStr1
  regsub -all "\u00b8" ${sStr1} {\&cedil;}  sStr2
  regsub -all "\u00b9" ${sStr2} {\&sup1;}   sStr1
  regsub -all "\u00ba" ${sStr1} {\&ordm;}   sStr2
  regsub -all "\u00bc" ${sStr2} {\&frac14;} sStr1
  regsub -all "\u00bd" ${sStr1} {\&frac12;} sStr2
  regsub -all "\u00be" ${sStr2} {\&frac34;} sStr1
  regsub -all "\u00bf" ${sStr1} {\&iquest;} sStr2
  regsub -all "\u00a1" ${sStr2} {\&iexcl;}  sStr1
  return ${sStr1}
}
